export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
// This is so you can do something like -  let myVar: INCREMENT_ENTHUSIASM;
// typeof INCREMENT_ENTHUSIASM returns "INCREMENT_ENTHUSIASM"
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const FETCH_WEATHER = 'FETCH_WEATHER';
export type FETCH_WEATHER = typeof FETCH_WEATHER;